version: '3.9'

services:
  api:
    image: ideahub-django-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"